[package]
name = "metropogen"
version = "0.1.0"
authors = ["Theodore Mason <tmason@pdx.edu>"]

[dependencies]
rand = "0.5"
serde = "1.0.70"
serde_json = "1.0.7"
serde_derive = "1.0.7"
include_dir = "0.2.1"
clap = "2.32.0"
textwrap = "0.10"
